### ISSUE TITLE
Extra whitespace on the style="width: 12%;"

### ISSUE THREAD

**Issue by juwara0** [BryanCrotaz/ember-cli-csp-style#1]
When writing an integration test for a component that is using the "styleBindings: ['width[%]']", I found that my expected values do not matching the actual result.

assert.strictEqual(
        Ember.$.trim( grandchild.attr( 'style' ) ),
        'width: 12%;',
        '"style" is "width: 12%;"'
    );

Without wrapping this in an Ember.trim(), even though the expected and actual appear to be an exact match my assertion fails. This leads me to think that there are some extra whitespace characters.

**Comment by BryanCrotaz** [comment]
The component uses Dom methods to change the style so that we're csp compliant. We don't format strings

**Comment by juwara0** [comment]
The interesting thing was that the assertion was successful when testing in the browser with ember serve but failed in the Terminal with ember test

**Comment by BryanCrotaz** [comment]
So that's
