### ISSUE TITLE
SafeString Deprecation with Ember 2.8

### ISSUE THREAD

**Issue by rwwagner90** [BryanCrotaz/ember-cli-csp-style#3]
I am getting a bunch of deprecations for this `DEPRECATION: Ember.Handlebars.SafeString is deprecated in favor of Ember.String.htmlSafe`

It is caused by this check https://github.com/BryanCrotaz/ember-cli-csp-style/blob/master/addon/mixins/observers/style.js#L46

**Comment by rwwagner90** [comment]
Submitted a PR to fix the issue

**Comment by dbashford** [comment]
👍
